version: '3.8'

volumes:
  static_volume:
  media_volume:
  frontend_volume:
  pg_volume:
    external: true

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 5s
       timeout: 5s
       retries: 5

  backend:
    image: 7ide/friends-locator-backend:latest
    restart: always
    volumes:
      - static_volume:/app/backend_static/
      - media_volume:/app/media/
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: 7ide/friends-locator-frontend:latest
    volumes:
      - frontend_volume:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_volume:/usr/share/nginx/html/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - static_volume:/var/html/backend_static/
      - media_volume:/var/html/media/

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
