# Generated by Django 4.1 on 2023-07-20 21:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=50,
                        unique=True,
                        verbose_name="Название места",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        help_text="Укажите широту",
                        validators=[
                            django.core.validators.MinValueValidator(-90.1),
                            django.core.validators.MaxValueValidator(90.1),
                        ],
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        help_text="Укажите долготу",
                        validators=[
                            django.core.validators.MinValueValidator(-180.1),
                            django.core.validators.MaxValueValidator(90.1),
                        ],
                        verbose_name="Долгота",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SharedPlaces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sharing_place",
                    models.ForeignKey(
                        help_text="Введите место",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_place",
                        to="places.place",
                        verbose_name="Место",
                    ),
                ),
                (
                    "sharing_to_user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing_to",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "sharing_user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sharing",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="sharedplaces",
            constraint=models.UniqueConstraint(
                fields=("sharing_user", "sharing_to_user", "sharing_place"),
                name="sharing-place",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="user_place"
            ),
        ),
    ]
